import type { Dict } from "./nl";

export const en: Dict = {
  org: {
    name: "Stichting Zurali Chej",
    tagline: "Strong women. Strong youth. Strong community.",
    short: "Zurali Chej",
  },
  common: {
    donate: "Donate",
    readMore: "Read more",
    viewAll: "View all",
    send: "Send",
    sent: "Thank you — we will get back to you as soon as possible.",
    menu: "Open menu",
    close: "Close menu",
    language: "Language",
    skip: "Skip to main content",
    contactUs: "Get in touch",
    partnerWith: "Become a partner",
  },
  nav: {
    home: "Home",
    over: "About the organisation",
    missie: "Mission & Vision",
    vrouwen: "Women & Youth",
    projecten: "Projects",
    internationaal: "International Cooperation",
    nieuws: "News",
    evenementen: "Events",
    kennisbank: "Knowledge base",
    partners: "Partners",
    vrijwilligers: "Volunteers",
    doneren: "Donate",
    contact: "Contact",
  },
  navGroups: {
    organisatie: "Organisation",
    werk: "Our work",
    meedoen: "Get involved",
  },
  home: {
    badge: "Roma-led · The Netherlands & Europe",
    title: "We strengthen Roma and Sinti",
    accent: "women and youth.",
    intro:
      "Stichting Zurali Chej is a Roma-led organisation based in the Netherlands and active across Europe. We work on empowerment, advocacy, education, awareness and international cooperation.",
    ctaPrimary: "Explore our projects",
    ctaSecondary: "About the organisation",
    heroAlt: "Roma and Sinti women in conversation during a gathering",
    stats: [
      { value: "12+", label: "Projects in the Netherlands and Europe" },
      { value: "6", label: "Italian cities with delivered programmes" },
      { value: "800+", label: "Women and young people reached" },
      { value: "25", label: "Partners, municipalities and funds" },
    ],
    pillarsTitle: "What we stand for",
    pillarsIntro:
      "Five pillars shape everything we do — locally in the neighbourhood, nationally at the table and internationally in partnership.",
    pillars: [
      {
        icon: "spark",
        title: "Empowerment",
        text: "Training, coaching and gatherings where women and young people discover their own strength and voice.",
      },
      {
        icon: "megaphone",
        title: "Advocacy",
        text: "We bring the voice of Roma and Sinti to municipalities, ministries and European institutions.",
      },
      {
        icon: "graduation",
        title: "Education",
        text: "School support, language help and guest lessons on Roma and Sinti history and culture.",
      },
      {
        icon: "film",
        title: "Awareness",
        text: "Film screenings, dialogue meetings and campaigns that break through stereotypes.",
      },
      {
        icon: "globe",
        title: "International cooperation",
        text: "Knowledge exchange and joint projects with European partner organisations.",
      },
      {
        icon: "hands",
        title: "Community",
        text: "A safe place for meeting, storytelling and passing culture on to new generations.",
      },
    ],
    focusTitle: "Our work at a glance",
    focus: [
      {
        title: "Women & Youth",
        text: "Personal guidance, empowerment circles and talent development for Roma and Sinti women and young people.",
        cta: "See the programme",
      },
      {
        title: "Projects",
        text: "From neighbourhood programmes to national campaigns and European cooperation projects.",
        cta: "See projects",
      },
      {
        title: "International Cooperation",
        text: "Exchange, research and joint delivery with partners in Italy, Romania, Serbia and beyond.",
        cta: "See cooperation",
      },
    ],
    impactEyebrow: "Impact",
    impactTitle: "Why this work is still needed",
    impactText:
      "Roma and Sinti remain among the most vulnerable minorities in Europe. Educational disadvantage, exclusion from the labour market and persistent stereotypes limit opportunity — especially for women and young people.",
    impactPoints: [
      "We offer support rooted in the lived reality of the community itself.",
      "We share knowledge with municipalities, schools and civil society organisations.",
      "We make the history, culture and position of Roma and Sinti visible.",
      "We build lasting European partnerships that outlive a single project.",
    ],
    newsTitle: "Latest news",
    eventsTitle: "Upcoming events",
    partnersTitle: "Together with",
    partnersText: "We work with municipalities, funds, knowledge institutions and European partner organisations.",
    ctaTitle: "Build equal opportunity with us",
    ctaText:
      "Become a partner, sign up as a volunteer or support our work with a donation. Every contribution widens the space for Roma and Sinti women and youth.",
    ctaButton: "Support our work",
  },
  over: {
    eyebrow: "About the organisation",
    title: "A Roma-led foundation,",
    accent: "rooted in the community.",
    intro:
      "Stichting Zurali Chej — 'strong girl' in Romanes — was founded to strengthen the position of Roma and Sinti women and young people. We work locally, nationally and across Europe.",
    storyTitle: "Our story",
    story: [
      "The foundation grew out of the community itself. What began as informal gatherings between Roma and Sinti women became a professional organisation that today works with municipalities, ministries, schools and European partners.",
      "We believe change starts with the people it concerns. That is why our programmes are designed and delivered by Roma and Sinti themselves, in close dialogue with the women and young people taking part.",
      "Alongside our work in the Netherlands we develop international projects and knowledge exchange across Europe. Several projects have already been delivered in different Italian cities, with local Roma organisations as co-implementers.",
    ],
    valuesTitle: "Core values",
    values: [
      { title: "Connection", text: "We bring people, generations and organisations together." },
      { title: "Inclusion", text: "Everyone takes part — no conditions up front." },
      { title: "Respect", text: "We work from equality and listen first." },
      { title: "Equality", text: "Not talking about the community, but working with it." },
      { title: "Empowerment", text: "We strengthen self-reliance instead of dependency." },
      { title: "Diversity", text: "Roma, Sinti and wider society in one conversation." },
    ],
    timelineTitle: "Milestones",
    timeline: [
      { year: "2019", title: "First women's circle", text: "Informal gatherings between Roma and Sinti women in the Netherlands." },
      { year: "2021", title: "Foundation established", text: "Formal establishment of Stichting Zurali Chej with its own board." },
      { year: "2023", title: "First European project", text: "Start of knowledge exchange with Roma organisations in Italy." },
      { year: "2025", title: "National network", text: "Structural cooperation with municipalities and knowledge institutions." },
      { year: "2026", title: "Digital platform", text: "Launch of this platform as the central place for our community." },
    ],
    teamTitle: "Who we are",
    team: [
      { name: "Laura Hamidovic", role: "Founder, director & project lead", text: "Responsible for strategy, European cooperation and advocacy." },
      { name: "Programme team", role: "Women & youth", text: "Runs empowerment circles, coaching and educational support." },
      { name: "Board", role: "Oversight & governance", text: "Safeguards the mission, the finances and the quality of our programmes." },
    ],
    governanceTitle: "Governance & accountability",
    governance: [
      "Our annual accounts and activity report are adopted by the board each year.",
      "We work according to the Dutch Governance Code and the GDPR in all data processing.",
      "Projects are funded by municipalities, national funds and European grant programmes.",
    ],
  },
  missie: {
    eyebrow: "Mission & Vision",
    title: "Equal opportunity for Roma and",
    accent: "Sinti women and youth.",
    intro:
      "Our mission and vision guide every project, every gathering and every partnership we enter into.",
    missionTitle: "Our mission",
    missionText:
      "We strengthen the position of Roma and Sinti women and young people through empowerment, advocacy, education, awareness and international cooperation. We create space in which they can develop their own voice, talent and future.",
    visionTitle: "Our vision",
    visionText:
      "We see a Europe in which Roma and Sinti participate fully: at school, at work, in governance and in public debate. A society where culture and history are known and respected, and where women and young people lead the change.",
    goalsTitle: "Our goals",
    goals: [
      "Inform, strengthen and connect Roma and Sinti women and young people.",
      "Increase the visibility of the community and the organisation.",
      "Make national and European projects visible and transferable.",
      "Encourage new partnerships with governments and organisations.",
      "Raise awareness of Roma and Sinti history, culture and position.",
      "Give funds and governments insight into our social impact.",
    ],
    approachTitle: "How we work",
    approach: [
      { step: "01", title: "Listen", text: "We start with the needs of the community, not with a funding framework." },
      { step: "02", title: "Co-design", text: "Women and young people help shape content, format and delivery." },
      { step: "03", title: "Deliver", text: "Programmes are run by people from the community itself." },
      { step: "04", title: "Share", text: "Knowledge and results are shared with partners in the Netherlands and Europe." },
    ],
    principlesTitle: "What you can expect from us",
    principles: [
      "A safe, accessible and respectful environment for everyone.",
      "Programmes that match language, culture and lived experience.",
      "Transparent accountability for resources and results.",
      "Lasting cooperation instead of one-off interventions.",
    ],
  },
  vrouwen: {
    eyebrow: "Women & Youth",
    title: "Room to grow,",
    accent: "at your own pace.",
    intro:
      "Our programmes are for Roma and Sinti women and young people who want to learn, start something, study or simply meet others. Taking part is always free.",
    womenTitle: "For women",
    womenText:
      "From empowerment circles and language support to help finding work or arranging care and schooling for your children. You decide what you need.",
    womenItems: [
      "Monthly women's circles in several cities",
      "Personal coaching and support in dealing with institutions",
      "Workshops on entrepreneurship, finances and digital skills",
      "Support after experiences of discrimination or domestic violence",
    ],
    youthTitle: "For young people",
    youthText:
      "Young people drive change. We offer talent programmes, study support and the chance to join European exchanges.",
    youthItems: [
      "Homework and study support, including after dropping out",
      "Talent and leadership track for young people aged 15 to 27",
      "European youth exchanges and training",
      "Media and storytelling lab: tell your own story",
    ],
    supportTitle: "How we support",
    support: [
      { icon: "hands", title: "Personal contact", text: "A fixed contact person who speaks your language and understands your situation." },
      { icon: "shield", title: "Safe and confidential", text: "What you share stays within the support relationship, unless you decide otherwise." },
      { icon: "graduation", title: "Practical help", text: "Joining you at appointments, understanding letters, submitting applications." },
      { icon: "spark", title: "Growing further", text: "From participant to volunteer, trainer or project lead." },
    ],
    storiesTitle: "Voices from the community",
    stories: [
      { quote: "For the first time I sat in a room where I did not have to explain who I am.", name: "Women's circle participant", place: "Rotterdam" },
      { quote: "Because of the exchange in Italy I now know I can build something for others too.", name: "Youth programme participant", place: "Utrecht" },
      { quote: "The support helped me get my daughter back into school.", name: "Mother of two", place: "The Hague" },
    ],
    joinTitle: "Want to join?",
    joinText:
      "Send us a message or drop by one of our gatherings. You can join at any time, with or without prior experience.",
    joinCta: "Get in touch",
  },
  projecten: {
    eyebrow: "Projects",
    title: "Programmes that",
    accent: "make a difference.",
    intro:
      "From neighbourhood empowerment to European knowledge exchange. Below is an overview of ongoing and completed projects.",
    filterAll: "All projects",
    filterLabel: "Filter by theme",
    countLabel: "projects",
    empty: "There are no projects in this theme yet.",
    statusRunning: "Ongoing",
    statusDone: "Completed",
    themes: ["Empowerment", "Education", "Awareness", "Advocacy", "International"],
    items: [
      {
        title: "Zurali — women's circles in the neighbourhood",
        theme: "Empowerment",
        place: "Amsterdam, Rotterdam, Utrecht",
        year: "2023 – present",
        status: "Ongoing",
        summary:
          "Monthly gatherings where Roma and Sinti women share experiences, follow training and support each other practically.",
      },
      {
        title: "Back to school",
        theme: "Education",
        place: "The Hague & Eindhoven",
        year: "2024 – present",
        status: "Ongoing",
        summary:
          "Study support and mediation between families and schools to reduce dropout among Roma and Sinti children.",
      },
      {
        title: "Our story on screen",
        theme: "Awareness",
        place: "Nationwide",
        year: "2024 – present",
        status: "Ongoing",
        summary:
          "Film screenings with post-screening dialogue about Roma and Sinti history, including persecution during the Second World War.",
      },
      {
        title: "A voice at the table",
        theme: "Advocacy",
        place: "Municipalities & ministries",
        year: "2023 – present",
        status: "Ongoing",
        summary:
          "Advisory tracks in which Roma and Sinti women speak directly with policymakers about education, housing and care.",
      },
      {
        title: "Chej Europa — exchange with Italy",
        theme: "International",
        place: "Rome, Naples, Milan, Bologna",
        year: "2023 – 2025",
        status: "Completed",
        summary:
          "Multi-year cooperation with Italian Roma organisations: training, joint research and youth exchanges across six cities.",
      },
      {
        title: "Digitally strong",
        theme: "Education",
        place: "Rotterdam",
        year: "2024 – 2025",
        status: "Completed",
        summary:
          "Digital skills for women: from government portals and healthcare systems to applying for jobs and staying safe online.",
      },
      {
        title: "Young leaders",
        theme: "Empowerment",
        place: "Nationwide",
        year: "2025 – present",
        status: "Ongoing",
        summary:
          "Leadership track for young people aged 15 to 27 with training, mentoring and their own neighbourhood project.",
      },
      {
        title: "Remembering together",
        theme: "Awareness",
        place: "Netherlands & Europe",
        year: "2022 – present",
        status: "Ongoing",
        summary:
          "Annual commemorations and teaching materials about the Porajmos, the genocide of Roma and Sinti.",
      },
    ],
    ctaTitle: "Develop a project together?",
    ctaText: "We are glad to work with municipalities, schools and European partners on new programmes.",
    ctaButton: "Schedule a conversation",
  },
  internationaal: {
    eyebrow: "International Cooperation",
    title: "One community,",
    accent: "across borders.",
    intro:
      "Roma and Sinti live all across Europe. Our challenges cross borders, and so do our solutions. We work with organisations, universities and municipalities in several countries.",
    italyTitle: "Projects in Italy",
    italyText:
      "In recent years several projects have been delivered in different Italian cities together with local Roma organisations. The programmes focused on women's empowerment, education and youth participation.",
    italyCities: ["Rome", "Naples", "Milan", "Bologna", "Turin", "Palermo"],
    networkTitle: "What we do together",
    network: [
      { icon: "globe", title: "Knowledge exchange", text: "Study visits and training in which methods are shared between countries." },
      { icon: "graduation", title: "Joint programmes", text: "Projects delivered and evaluated in several countries at the same time." },
      { icon: "megaphone", title: "European advocacy", text: "Joint input towards European institutions and national strategies." },
      { icon: "hands", title: "Youth exchange", text: "Young people meet peers from other countries and build their own network." },
    ],
    partnersTitle: "Countries where we work or cooperate",
    countries: ["Netherlands", "Italy", "Romania", "Serbia", "Germany", "North Macedonia", "Spain", "Slovakia"],
    fundingTitle: "Funding & frameworks",
    funding: [
      "European programmes such as Erasmus+ and CERV for exchange and participation.",
      "National funds and municipal grants for local delivery.",
      "Alignment with the EU Roma strategic framework 2020–2030.",
    ],
    ctaTitle: "Submit a European project together?",
    ctaText: "We are available as a partner or co-applicant in European grant applications.",
    ctaButton: "Get in touch",
  },
  nieuws: {
    eyebrow: "News",
    title: "What is happening at",
    accent: "Zurali Chej.",
    intro: "Updates on our projects, positions, partnerships and the community.",
    filterAll: "All",
    empty: "No posts in this category.",
    items: [
      {
        date: "18 July 2026",
        category: "International",
        title: "Closing the multi-year exchange programme with Italy",
        excerpt:
          "After three years of cooperation across six Italian cities we share the results, the method and the lessons for future European projects.",
      },
      {
        date: "2 July 2026",
        category: "Education",
        title: "Guest lessons on Roma and Sinti history now in secondary schools",
        excerpt:
          "Together with teachers we developed material on culture, history and the Porajmos, including a guest lesson given by young people themselves.",
      },
      {
        date: "12 June 2026",
        category: "Advocacy",
        title: "Our input into municipal inclusion policy",
        excerpt:
          "Women from our circles spoke with city officials about housing, education and how institutions treat the community.",
      },
      {
        date: "28 May 2026",
        category: "Community",
        title: "New women's circle starting in Eindhoven",
        excerpt:
          "From June a group will gather every month in Eindhoven. No registration needed — you are welcome.",
      },
      {
        date: "6 May 2026",
        category: "Awareness",
        title: "Film evening and dialogue drew a full house",
        excerpt:
          "More than a hundred visitors watched the documentary and afterwards spoke with makers, young people and policymakers.",
      },
      {
        date: "14 April 2026",
        category: "Organisation",
        title: "Annual report 2025 published",
        excerpt:
          "Our activity report and financial accountability for 2025 are available in the knowledge base.",
      },
    ],
    newsletterTitle: "Stay informed",
    newsletterText: "Receive our newsletter four times a year with projects, events and calls to action.",
  },
  evenementen: {
    eyebrow: "Events",
    title: "Come by,",
    accent: "you are welcome.",
    intro:
      "Women's circles, film screenings, dialogue meetings and training. Most gatherings are free and open to all.",
    filterAll: "All types",
    cityLabel: "City",
    allCities: "All cities",
    countLabel: "gatherings",
    empty: "No gatherings match this combination.",
    freeLabel: "Free",
    types: ["Women's circle", "Film & dialogue", "Training", "Youth", "Commemoration"],
    items: [
      { day: "12", month: "AUG", type: "Commemoration", title: "Porajmos commemoration", city: "Amsterdam", time: "19:00 – 21:00", text: "Annual commemoration of the genocide of Roma and Sinti, with music and testimony." },
      { day: "22", month: "AUG", type: "Women's circle", title: "Women's circle Rotterdam", city: "Rotterdam", time: "10:30 – 13:00", text: "Meeting, coffee and a workshop on work and education." },
      { day: "05", month: "SEP", type: "Film & dialogue", title: "Film evening: our history", city: "Utrecht", time: "19:30 – 22:00", text: "Documentary with a discussion led by young people from the community." },
      { day: "17", month: "SEP", type: "Training", title: "Digital skills training", city: "The Hague", time: "13:00 – 16:00", text: "Practical training on government portals, healthcare systems and job applications." },
      { day: "28", month: "SEP", type: "Youth", title: "Young leaders — opening session", city: "Eindhoven", time: "15:00 – 18:00", text: "Introduction to the leadership track for young people aged 15 to 27." },
      { day: "09", month: "OCT", type: "Women's circle", title: "Women's circle Eindhoven", city: "Eindhoven", time: "10:30 – 13:00", text: "New monthly group — walk in, no registration needed." },
      { day: "21", month: "OCT", type: "Training", title: "Guest lesson training for youth", city: "Amsterdam", time: "14:00 – 17:00", text: "Learn to tell your own story to secondary school classes." },
      { day: "07", month: "NOV", type: "Film & dialogue", title: "Dialogue meeting with municipalities", city: "Utrecht", time: "16:00 – 19:00", text: "Policymakers and community in conversation about inclusion and trust." },
    ],
    noteTitle: "Practical",
    notes: [
      "All venues are wheelchair accessible. Let us know if you need other support.",
      "Children are welcome; childcare is available at most gatherings.",
      "Need transport? Get in touch and we will think along with you.",
    ],
  },
  kennisbank: {
    eyebrow: "Knowledge base",
    title: "Knowledge about Roma",
    accent: "and Sinti, free to use.",
    intro:
      "Publications, teaching materials, research and guides for schools, municipalities, journalists and the community itself.",
    filterAll: "All materials",
    empty: "No materials in this category yet.",
    typeLabel: "Type",
    types: ["Publication", "Teaching material", "Research", "Guide", "Accountability"],
    items: [
      { type: "Teaching material", title: "Lesson pack: history of Roma and Sinti", meta: "PDF · secondary education", text: "Four lessons on origins, culture, persecution and the position of Roma and Sinti today." },
      { type: "Guide", title: "Guide for municipalities", meta: "PDF · 24 pages", text: "How do you reach and involve Roma and Sinti residents in education, housing and care policy?" },
      { type: "Research", title: "Educational participation of Roma girls", meta: "Report · 2025", text: "Exploratory research into the causes of school dropout and effective interventions." },
      { type: "Publication", title: "Zurali — stories of strong women", meta: "Digital magazine", text: "Portraits of women from our circles in the Netherlands, Italy and Romania." },
      { type: "Guide", title: "Media guide: writing about Roma and Sinti", meta: "PDF · for journalists", text: "Terminology, common stereotypes and recommendations for careful reporting." },
      { type: "Accountability", title: "Annual report 2025", meta: "PDF · activities & finances", text: "Overview of our activities, results and use of resources in 2025." },
    ],
    themesTitle: "Frequently requested themes",
    themes: [
      { title: "History & Porajmos", text: "Background on the persecution of Roma and Sinti and its lasting effects." },
      { title: "Education", text: "Dropout, language support and cooperation between school and family." },
      { title: "Antigypsyism", text: "Recognising and addressing discrimination against Roma and Sinti." },
      { title: "Culture & language", text: "Romanes, music, traditions and passing them on to young people." },
    ],
    requestTitle: "Request materials",
    requestText:
      "Would you like to use material for your school, municipality or organisation? Get in touch — we are happy to add a guest lesson or workshop.",
  },
  partners: {
    eyebrow: "Partners",
    title: "Working together makes",
    accent: "us stronger.",
    intro:
      "We work with municipalities, funds, knowledge institutions, schools and European partner organisations. Together we reach further than alone.",
    groups: [
      { title: "Government & municipalities", items: ["City of Amsterdam", "City of Rotterdam", "City of Utrecht", "City of The Hague", "Ministry of Social Affairs"] },
      { title: "Funds", items: ["Erasmus+", "CERV programme", "Oranje Fonds", "VSBfonds", "Local participation funds"] },
      { title: "Knowledge & education", items: ["University research groups", "Secondary schools", "Vocational colleges", "Public libraries"] },
      { title: "European partners", items: ["Roma organisations Italy", "Network Romania", "Network Serbia", "German Sinti organisations"] },
    ],
    whyTitle: "What a partnership delivers",
    why: [
      { icon: "hands", title: "Access to the community", text: "We reach people who are not reached through regular channels." },
      { icon: "graduation", title: "Expertise", text: "Knowledge of culture, language and effective approaches, directly applicable in policy." },
      { icon: "globe", title: "European network", text: "Direct lines to organisations in several European countries." },
      { icon: "shield", title: "Careful delivery", text: "Transparent accountability and clear agreements on results." },
    ],
    formTitle: "Become a partner",
    formText: "Tell us briefly what you have in mind. We respond within five working days.",
    fields: { org: "Organisation", name: "Contact person", email: "Email address", type: "Type of cooperation", message: "Details" },
    types: ["Local project", "Research or knowledge sharing", "European grant application", "Financial support", "Other"],
  },
  vrijwilligers: {
    eyebrow: "Volunteers",
    title: "Your time makes",
    accent: "an immediate difference.",
    intro:
      "Volunteers are essential to our gatherings, support work and projects. Experience is not required — commitment is.",
    rolesTitle: "Where we need help",
    roles: [
      { title: "Women's circle host", time: "One half-day per month", text: "Help organise a monthly gathering and welcome participants." },
      { title: "Homework tutor", time: "2 hours per week", text: "Support children and young people with school, language and homework." },
      { title: "Interpreter or language buddy", time: "By arrangement", text: "Romanes, Romanian, Serbian or Italian? Help during conversations with institutions." },
      { title: "Events support", time: "Per gathering", text: "Setup, welcome and catering at film evenings and commemorations." },
      { title: "Communications", time: "2 – 4 hours per week", text: "Help with social media, photography or writing news posts." },
      { title: "Fundraising", time: "By arrangement", text: "Support grant applications and contact with funds." },
    ],
    offerTitle: "What we offer",
    offer: [
      "A warm community and direct involvement with the people it concerns.",
      "Introduction, guidance and training you can use elsewhere too.",
      "Travel expenses reimbursed and a volunteer agreement.",
      "The chance to grow into a project role.",
    ],
    stepsTitle: "How signing up works",
    steps: [
      { step: "01", title: "Sign up", text: "Fill in the form or send us a message." },
      { step: "02", title: "Introduction call", text: "A conversation about your wishes, time and background." },
      { step: "03", title: "Orientation", text: "You join a gathering and are paired with a mentor." },
      { step: "04", title: "Get started", text: "You start in your role, with fixed moments for check-ins." },
    ],
    formTitle: "Sign up as a volunteer",
    fields: { name: "Name", email: "Email address", phone: "Phone number", role: "Role you would like to help with", message: "Tell us about yourself" },
  },
  doneren: {
    eyebrow: "Donate",
    title: "Support strong women",
    accent: "and young people.",
    intro:
      "Your donation funds women's circles, study support, film evenings and European exchanges. Every contribution goes directly into our programmes.",
    amountTitle: "Choose an amount",
    amounts: [
      { value: "€ 15", label: "One participant", text: "Transport and catering for one woman at a gathering." },
      { value: "€ 40", label: "One workshop", text: "Materials for a digital skills workshop." },
      { value: "€ 100", label: "One women's circle", text: "A complete monthly gathering in one city." },
      { value: "€ 250", label: "One young person", text: "Participation of a young person in a European exchange." },
    ],
    otherAmount: "Other amount",
    monthly: "Donate monthly",
    once: "Donate once",
    donateCta: "Donate now",
    donateNote:
      "The online donation platform is currently being set up. Until then you can transfer directly or contact us.",
    bankTitle: "Direct bank transfer",
    bank: [
      { label: "Account name", value: "Stichting Zurali Chej" },
      { label: "IBAN", value: "NL00 BANK 0000 0000 00" },
      { label: "Reference", value: "Donation + your name" },
    ],
    waysTitle: "Other ways to support",
    ways: [
      { icon: "heart", title: "Periodic giving", text: "A periodic gift gives us certainty over several years." },
      { icon: "handshake", title: "Corporate partnership", text: "Support a project with resources, expertise or a venue." },
      { icon: "hands", title: "Donate your time", text: "Volunteers are just as valuable as financial support." },
      { icon: "spark", title: "Fundraise", text: "Organise an action at work, at school or on your birthday." },
    ],
    trustTitle: "Where does your money go?",
    trust: [
      { value: "78%", label: "Directly into programmes for women and youth" },
      { value: "14%", label: "Knowledge sharing, awareness and materials" },
      { value: "8%", label: "Organisation and accountability" },
    ],
    trustNote:
      "We account for our spending each year in the annual report, which you will find in the knowledge base.",
  },
  contact: {
    eyebrow: "Contact",
    title: "We would love to hear",
    accent: "from you.",
    intro:
      "A question about a gathering, a request to work together or a need for support? Write to us — a real person always answers.",
    channels: [
      { icon: "mail", title: "General questions", value: "info@zuralichej.nl", note: "Reply within two working days" },
      { icon: "hands", title: "Support & guidance", value: "support@zuralichej.nl", note: "Confidential, also in Romanes" },
      { icon: "handshake", title: "Partners & press", value: "partners@zuralichej.nl", note: "Cooperation, media and funds" },
    ],
    formTitle: "Send a message",
    fields: { name: "Your name", email: "Email address", subject: "Subject", message: "Message" },
    subjects: [
      "Support for myself or my family",
      "Joining a gathering",
      "Cooperation or partnership",
      "Press or research",
      "Volunteering",
      "Something else",
    ],
    privacy: "We handle your data carefully and never share it with third parties (GDPR).",
    visitTitle: "Visiting address",
    address: ["Stichting Zurali Chej", "PO Box 1234", "1000 AB Amsterdam", "The Netherlands"],
    hoursTitle: "Availability",
    hours: [
      { label: "Mon – Thu", value: "09:00 – 17:00" },
      { label: "Friday", value: "09:00 – 13:00" },
      { label: "Phone", value: "+31 20 000 0000" },
    ],
    kvkTitle: "Details",
    kvk: [
      { label: "Chamber of Commerce", value: "00000000" },
      { label: "RSIN", value: "000000000" },
      { label: "IBAN", value: "NL00 BANK 0000 0000 00" },
    ],
  },
  footer: {
    about:
      "Stichting Zurali Chej is a Roma-led organisation working for Roma and Sinti women and young people in the Netherlands and across Europe.",
    newsletterTitle: "Newsletter",
    newsletterText: "The latest news in your inbox four times a year.",
    newsletterPlaceholder: "Your email address",
    newsletterButton: "Subscribe",
    newsletterSuccess: "Thank you — you are subscribed.",
    rights: "All rights reserved.",
    privacy: "Privacy statement",
    accessibility: "Accessibility",
  },
};
