export const nl = {
  org: {
    name: "Stichting Zurali Chej",
    tagline: "Sterke vrouwen. Sterke jongeren. Sterke gemeenschap.",
    short: "Zurali Chej",
  },
  common: {
    donate: "Doneren",
    readMore: "Lees meer",
    viewAll: "Bekijk alles",
    send: "Versturen",
    sent: "Dank je wel — we nemen zo snel mogelijk contact met je op.",
    menu: "Menu openen",
    close: "Menu sluiten",
    language: "Taal",
    skip: "Ga naar hoofdinhoud",
    contactUs: "Neem contact op",
    partnerWith: "Word partner",
  },
  nav: {
    home: "Home",
    over: "Over de organisatie",
    missie: "Missie & Visie",
    vrouwen: "Vrouwen & Jongeren",
    projecten: "Projecten",
    internationaal: "Internationale Samenwerking",
    nieuws: "Nieuws",
    evenementen: "Evenementen",
    kennisbank: "Kennisbank",
    partners: "Partners",
    vrijwilligers: "Vrijwilligers",
    doneren: "Doneren",
    contact: "Contact",
  },
  navGroups: {
    organisatie: "Organisatie",
    werk: "Ons werk",
    meedoen: "Meedoen",
  },
  home: {
    badge: "Door Roma geleid · Nederland & Europa",
    title: "Wij versterken Roma- en Sinti-",
    accent: "vrouwen en jongeren.",
    intro:
      "Stichting Zurali Chej is een door Roma geleide organisatie in Nederland, actief in heel Europa. Wij werken aan empowerment, belangenbehartiging, educatie, bewustwording en internationale samenwerking.",
    ctaPrimary: "Ontdek onze projecten",
    ctaSecondary: "Over de organisatie",
    heroAlt: "Roma- en Sinti-vrouwen in gesprek tijdens een bijeenkomst",
    stats: [
      { value: "12+", label: "Projecten in Nederland en Europa" },
      { value: "6", label: "Steden in Italië met uitgevoerde programma's" },
      { value: "800+", label: "Vrouwen en jongeren bereikt" },
      { value: "25", label: "Partners, gemeenten en fondsen" },
    ],
    pillarsTitle: "Waar wij voor staan",
    pillarsIntro:
      "Vijf pijlers vormen de basis van alles wat wij doen — lokaal in de wijk, nationaal aan tafel en Europees in samenwerking.",
    pillars: [
      {
        icon: "spark",
        title: "Empowerment",
        text: "Trainingen, coaching en ontmoeting waardoor vrouwen en jongeren hun eigen kracht en stem ontdekken.",
      },
      {
        icon: "megaphone",
        title: "Belangenbehartiging",
        text: "Wij brengen de stem van Roma en Sinti naar gemeenten, ministeries en Europese instellingen.",
      },
      {
        icon: "graduation",
        title: "Educatie",
        text: "Onderwijsondersteuning, taalhulp en gastlessen over de geschiedenis en cultuur van Roma en Sinti.",
      },
      {
        icon: "film",
        title: "Bewustwording",
        text: "Filmvertoningen, dialoogbijeenkomsten en campagnes die stereotypen doorbreken.",
      },
      {
        icon: "globe",
        title: "Internationale samenwerking",
        text: "Kennisuitwisseling en gezamenlijke projecten met Europese partnerorganisaties.",
      },
      {
        icon: "hands",
        title: "Gemeenschap",
        text: "Een veilige plek voor ontmoeting, verhalen en het doorgeven van cultuur aan nieuwe generaties.",
      },
    ],
    focusTitle: "Ons werk in het kort",
    focus: [
      {
        title: "Vrouwen & Jongeren",
        text: "Persoonlijke begeleiding, empowermentgroepen en talentontwikkeling voor Roma- en Sinti-vrouwen en jongeren.",
        cta: "Bekijk het programma",
      },
      {
        title: "Projecten",
        text: "Van wijkgerichte programma's tot landelijke campagnes en Europese samenwerkingsprojecten.",
        cta: "Bekijk projecten",
      },
      {
        title: "Internationale Samenwerking",
        text: "Uitwisseling, onderzoek en gezamenlijke uitvoering met partners in onder meer Italië, Roemenië en Servië.",
        cta: "Bekijk samenwerking",
      },
    ],
    impactEyebrow: "Impact",
    impactTitle: "Waarom dit werk nodig blijft",
    impactText:
      "Roma en Sinti behoren nog altijd tot de meest kwetsbare minderheden in Europa. Onderwijsachterstand, uitsluiting op de arbeidsmarkt en hardnekkige stereotypen beperken kansen — vooral voor vrouwen en jongeren.",
    impactPoints: [
      "Wij bieden ondersteuning die aansluit bij de leefwereld van de gemeenschap zelf.",
      "Wij delen kennis met gemeenten, scholen en maatschappelijke organisaties.",
      "Wij maken de geschiedenis, cultuur en positie van Roma en Sinti zichtbaar.",
      "Wij bouwen duurzame Europese samenwerkingen die verder gaan dan één project.",
    ],
    newsTitle: "Laatste nieuws",
    eventsTitle: "Aankomende evenementen",
    partnersTitle: "Samen met",
    partnersText: "Wij werken met gemeenten, fondsen, kennisinstellingen en Europese partnerorganisaties.",
    ctaTitle: "Bouw met ons aan gelijke kansen",
    ctaText:
      "Word partner, meld je aan als vrijwilliger of steun ons werk met een donatie. Elke bijdrage vergroot de ruimte voor Roma- en Sinti-vrouwen en jongeren.",
    ctaButton: "Steun ons werk",
  },
  over: {
    eyebrow: "Over de organisatie",
    title: "Een door Roma geleide stichting,",
    accent: "geworteld in de gemeenschap.",
    intro:
      "Stichting Zurali Chej — 'sterk meisje' in het Romanes — is opgericht om de positie van Roma- en Sinti-vrouwen en jongeren te versterken. Wij werken lokaal, nationaal en Europees.",
    storyTitle: "Ons verhaal",
    story: [
      "De stichting ontstond vanuit de gemeenschap zelf. Wat begon als informele ontmoetingen tussen Roma- en Sinti-vrouwen groeide uit tot een professionele organisatie die vandaag samenwerkt met gemeenten, ministeries, onderwijsinstellingen en Europese partners.",
      "Wij geloven dat verandering begint bij de mensen om wie het gaat. Daarom worden onze programma's ontworpen en uitgevoerd door Roma en Sinti zelf, in nauwe samenspraak met de vrouwen en jongeren die eraan deelnemen.",
      "Naast onze activiteiten in Nederland ontwikkelen wij internationale projecten en kennisuitwisseling binnen Europa. Zo zijn inmiddels meerdere projecten uitgevoerd in verschillende steden in Italië, met lokale Roma-organisaties als medeuitvoerders.",
    ],
    valuesTitle: "Kernwaarden",
    values: [
      { title: "Verbinding", text: "Wij brengen mensen, generaties en organisaties bij elkaar." },
      { title: "Inclusie", text: "Iedereen doet mee — zonder voorwaarden vooraf." },
      { title: "Respect", text: "Wij werken vanuit gelijkwaardigheid en luisteren eerst." },
      { title: "Gelijkwaardigheid", text: "Geen praten over, maar samen met de gemeenschap." },
      { title: "Empowerment", text: "Wij versterken eigen kracht in plaats van afhankelijkheid." },
      { title: "Diversiteit", text: "Roma, Sinti en de bredere samenleving in één gesprek." },
    ],
    timelineTitle: "Mijlpalen",
    timeline: [
      { year: "2019", title: "Eerste vrouwenkring", text: "Informele ontmoetingen tussen Roma- en Sinti-vrouwen in Nederland." },
      { year: "2021", title: "Oprichting stichting", text: "Formele oprichting van Stichting Zurali Chej met eigen bestuur." },
      { year: "2023", title: "Eerste Europese project", text: "Start van kennisuitwisseling met Roma-organisaties in Italië." },
      { year: "2025", title: "Landelijk netwerk", text: "Structurele samenwerking met gemeenten en kennisinstellingen." },
      { year: "2026", title: "Digitaal platform", text: "Lancering van dit platform als centrale plek voor onze gemeenschap." },
    ],
    teamTitle: "Wie wij zijn",
    team: [
      { name: "Laura Hamidovic", role: "Oprichter, directeur & projectleider", text: "Verantwoordelijk voor strategie, Europese samenwerking en belangenbehartiging." },
      { name: "Programmateam", role: "Vrouwen & jongeren", text: "Begeleidt empowermentgroepen, coaching en onderwijsondersteuning." },
      { name: "Bestuur", role: "Toezicht & governance", text: "Bewaakt de missie, de financiën en de kwaliteit van onze programma's." },
    ],
    governanceTitle: "Governance & verantwoording",
    governance: [
      "Onze jaarrekening en activiteitenverslag worden jaarlijks door het bestuur vastgesteld.",
      "Wij werken volgens de Governance Code Cultuur en de AVG bij alle gegevensverwerking.",
      "Projecten worden gefinancierd door gemeenten, landelijke fondsen en Europese subsidieprogramma's.",
    ],
  },
  missie: {
    eyebrow: "Missie & Visie",
    title: "Gelijke kansen voor Roma- en",
    accent: "Sinti-vrouwen en jongeren.",
    intro:
      "Onze missie en visie geven richting aan elk project, elke bijeenkomst en elke samenwerking die wij aangaan.",
    missionTitle: "Onze missie",
    missionText:
      "Wij versterken de positie van Roma- en Sinti-vrouwen en jongeren door empowerment, belangenbehartiging, educatie, bewustwording en internationale samenwerking. Wij creëren ruimte waarin zij hun eigen stem, talent en toekomst kunnen ontwikkelen.",
    visionTitle: "Onze visie",
    visionText:
      "Wij zien een Europa waarin Roma en Sinti volwaardig meedoen: op school, op het werk, in het bestuur en in het publieke debat. Een samenleving waarin cultuur en geschiedenis worden gekend en gerespecteerd, en waarin vrouwen en jongeren vooropgaan in verandering.",
    goalsTitle: "Onze doelen",
    goals: [
      "Roma- en Sinti-vrouwen en jongeren informeren, versterken en verbinden.",
      "De zichtbaarheid van de gemeenschap en de organisatie vergroten.",
      "Nationale en Europese projecten zichtbaar en overdraagbaar maken.",
      "Nieuwe partnerschappen met overheden en organisaties stimuleren.",
      "Bewustwording vergroten over geschiedenis, cultuur en positie van Roma en Sinti.",
      "Fondsen en overheden inzicht geven in onze maatschappelijke impact.",
    ],
    approachTitle: "Onze werkwijze",
    approach: [
      { step: "01", title: "Luisteren", text: "Wij starten bij de behoefte van de gemeenschap, niet bij een subsidiekader." },
      { step: "02", title: "Samen ontwerpen", text: "Vrouwen en jongeren denken mee over inhoud, vorm en uitvoering." },
      { step: "03", title: "Uitvoeren", text: "Programma's worden uitgevoerd door mensen uit de gemeenschap zelf." },
      { step: "04", title: "Delen", text: "Kennis en resultaten worden gedeeld met partners in Nederland en Europa." },
    ],
    principlesTitle: "Wat je van ons mag verwachten",
    principles: [
      "Een veilige, toegankelijke en respectvolle omgeving voor iedereen.",
      "Programma's die aansluiten bij taal, cultuur en leefwereld.",
      "Transparante verantwoording over middelen en resultaten.",
      "Duurzame samenwerking in plaats van eenmalige interventies.",
    ],
  },
  vrouwen: {
    eyebrow: "Vrouwen & Jongeren",
    title: "Ruimte om te groeien,",
    accent: "in je eigen tempo.",
    intro:
      "Onze programma's zijn er voor Roma- en Sinti-vrouwen en jongeren die willen leren, ondernemen, studeren of gewoon andere mensen willen ontmoeten. Deelname is altijd kosteloos.",
    womenTitle: "Voor vrouwen",
    womenText:
      "Van empowermentgroepen en taalondersteuning tot hulp bij het vinden van werk of het regelen van zorg en onderwijs voor je kinderen. Je bepaalt zelf wat je nodig hebt.",
    womenItems: [
      "Maandelijkse vrouwenkringen in verschillende steden",
      "Persoonlijke coaching en begeleiding bij instanties",
      "Workshops ondernemerschap, financiën en digitale vaardigheden",
      "Ondersteuning bij ervaringen met discriminatie of huiselijk geweld",
    ],
    youthTitle: "Voor jongeren",
    youthText:
      "Jongeren zijn de motor van verandering. Wij bieden talentprogramma's, studiebegeleiding en de kans om mee te doen aan Europese uitwisselingen.",
    youthItems: [
      "Huiswerk- en studiebegeleiding, ook bij schooluitval",
      "Talent- en leiderschapstraject voor jongeren van 15 tot 27 jaar",
      "Europese jongerenuitwisselingen en trainingen",
      "Media- en verhalenlab: vertel je eigen verhaal",
    ],
    supportTitle: "Hoe wij ondersteunen",
    support: [
      { icon: "hands", title: "Persoonlijk contact", text: "Een vast aanspreekpunt dat je taal spreekt en je situatie begrijpt." },
      { icon: "shield", title: "Veilig en vertrouwelijk", text: "Wat je deelt blijft binnen de begeleiding, tenzij jij anders wilt." },
      { icon: "graduation", title: "Praktische hulp", text: "Meegaan naar afspraken, brieven begrijpen, aanvragen indienen." },
      { icon: "spark", title: "Doorgroeien", text: "Van deelnemer naar vrijwilliger, trainer of projectleider." },
    ],
    storiesTitle: "Verhalen uit de gemeenschap",
    stories: [
      { quote: "Voor het eerst zat ik in een ruimte waar niemand me hoefde uit te leggen wie ik ben.", name: "Deelnemer vrouwenkring", place: "Rotterdam" },
      { quote: "Door de uitwisseling in Italië weet ik nu dat ik ook iets kan opbouwen voor anderen.", name: "Deelnemer jongerenprogramma", place: "Utrecht" },
      { quote: "De begeleiding hielp mij mijn dochter weer naar school te krijgen.", name: "Moeder van twee", place: "Den Haag" },
    ],
    joinTitle: "Meedoen?",
    joinText:
      "Stuur een bericht of loop binnen bij een van onze bijeenkomsten. Aanmelden kan altijd, ook zonder ervaring of papieren.",
    joinCta: "Neem contact op",
  },
  projecten: {
    eyebrow: "Projecten",
    title: "Programma's die",
    accent: "verschil maken.",
    intro:
      "Van wijkgerichte empowerment tot Europese kennisuitwisseling. Hieronder een overzicht van lopende en afgeronde projecten.",
    filterAll: "Alle projecten",
    filterLabel: "Filter op thema",
    countLabel: "projecten",
    empty: "Er zijn nog geen projecten binnen dit thema.",
    statusRunning: "Lopend",
    statusDone: "Afgerond",
    themes: ["Empowerment", "Educatie", "Bewustwording", "Belangenbehartiging", "Internationaal"],
    items: [
      {
        title: "Zurali — vrouwenkringen in de wijk",
        theme: "Empowerment",
        place: "Amsterdam, Rotterdam, Utrecht",
        year: "2023 – heden",
        status: "Lopend",
        summary:
          "Maandelijkse ontmoetingsgroepen waar Roma- en Sinti-vrouwen ervaringen delen, trainingen volgen en elkaar praktisch ondersteunen.",
      },
      {
        title: "Terug naar school",
        theme: "Educatie",
        place: "Den Haag & Eindhoven",
        year: "2024 – heden",
        status: "Lopend",
        summary:
          "Studiebegeleiding en bemiddeling tussen gezinnen en scholen om schooluitval onder Roma- en Sinti-kinderen terug te dringen.",
      },
      {
        title: "Ons verhaal op het doek",
        theme: "Bewustwording",
        place: "Landelijk",
        year: "2024 – heden",
        status: "Lopend",
        summary:
          "Filmvertoningen met nagesprek over de geschiedenis van Roma en Sinti, waaronder de vervolging in de Tweede Wereldoorlog.",
      },
      {
        title: "Stem aan tafel",
        theme: "Belangenbehartiging",
        place: "Gemeenten & ministeries",
        year: "2023 – heden",
        status: "Lopend",
        summary:
          "Adviestrajecten waarin Roma- en Sinti-vrouwen zelf met beleidsmakers in gesprek gaan over onderwijs, wonen en zorg.",
      },
      {
        title: "Chej Europa — uitwisseling Italië",
        theme: "Internationaal",
        place: "Rome, Napels, Milaan, Bologna",
        year: "2023 – 2025",
        status: "Afgerond",
        summary:
          "Meerjarige samenwerking met Italiaanse Roma-organisaties: trainingen, gezamenlijke onderzoeken en jongerenuitwisselingen in zes steden.",
      },
      {
        title: "Digitaal sterk",
        theme: "Educatie",
        place: "Rotterdam",
        year: "2024 – 2025",
        status: "Afgerond",
        summary:
          "Digitale vaardigheden voor vrouwen: van DigiD en zorgportalen tot online solliciteren en veilig omgaan met sociale media.",
      },
      {
        title: "Jonge leiders",
        theme: "Empowerment",
        place: "Landelijk",
        year: "2025 – heden",
        status: "Lopend",
        summary:
          "Leiderschapstraject voor jongeren van 15 tot 27 jaar met trainingen, mentoring en een eigen wijkproject.",
      },
      {
        title: "Herdenken en herinneren",
        theme: "Bewustwording",
        place: "Nederland & Europa",
        year: "2022 – heden",
        status: "Lopend",
        summary:
          "Jaarlijkse herdenkingsbijeenkomsten en lesmateriaal over de Porajmos, de genocide op Roma en Sinti.",
      },
    ],
    ctaTitle: "Samen een project ontwikkelen?",
    ctaText: "Wij werken graag met gemeenten, scholen en Europese partners aan nieuwe programma's.",
    ctaButton: "Plan een gesprek",
  },
  internationaal: {
    eyebrow: "Internationale Samenwerking",
    title: "Eén gemeenschap,",
    accent: "over grenzen heen.",
    intro:
      "Roma en Sinti wonen in heel Europa. Onze uitdagingen zijn grensoverschrijdend en dus zijn onze oplossingen dat ook. Wij werken samen met organisaties, universiteiten en gemeenten in meerdere landen.",
    italyTitle: "Projecten in Italië",
    italyText:
      "In de afgelopen jaren zijn meerdere projecten uitgevoerd in verschillende Italiaanse steden, in samenwerking met lokale Roma-organisaties. De programma's richtten zich op vrouwenempowerment, onderwijs en jongerenparticipatie.",
    italyCities: ["Rome", "Napels", "Milaan", "Bologna", "Turijn", "Palermo"],
    networkTitle: "Wat wij samen doen",
    network: [
      { icon: "globe", title: "Kennisuitwisseling", text: "Werkbezoeken en trainingen waarin methodieken worden gedeeld tussen landen." },
      { icon: "graduation", title: "Gezamenlijke programma's", text: "Projecten die tegelijk in meerdere landen worden uitgevoerd en geëvalueerd." },
      { icon: "megaphone", title: "Europese belangenbehartiging", text: "Gezamenlijke inbreng richting Europese instellingen en nationale strategieën." },
      { icon: "hands", title: "Jongerenuitwisseling", text: "Jongeren ontmoeten leeftijdsgenoten uit andere landen en bouwen een eigen netwerk." },
    ],
    partnersTitle: "Landen waar wij actief zijn of mee samenwerken",
    countries: ["Nederland", "Italië", "Roemenië", "Servië", "Duitsland", "Noord-Macedonië", "Spanje", "Slowakije"],
    fundingTitle: "Financiering & kaders",
    funding: [
      "Europese programma's zoals Erasmus+ en CERV voor uitwisseling en participatie.",
      "Nationale fondsen en gemeentelijke subsidies voor lokale uitvoering.",
      "Aansluiting bij de EU Roma strategic framework 2020–2030.",
    ],
    ctaTitle: "Een Europees project samen indienen?",
    ctaText: "Wij zijn beschikbaar als partner of medeaanvrager in Europese subsidietrajecten.",
    ctaButton: "Neem contact op",
  },
  nieuws: {
    eyebrow: "Nieuws",
    title: "Wat er speelt bij",
    accent: "Zurali Chej.",
    intro: "Updates over onze projecten, standpunten, samenwerkingen en de gemeenschap.",
    filterAll: "Alles",
    empty: "Geen berichten in deze categorie.",
    items: [
      {
        date: "18 juli 2026",
        category: "Internationaal",
        title: "Afsluiting van het meerjarige uitwisselingsprogramma met Italië",
        excerpt:
          "Na drie jaar samenwerking in zes Italiaanse steden delen wij de resultaten, de methodiek en de lessen voor toekomstige Europese projecten.",
      },
      {
        date: "2 juli 2026",
        category: "Educatie",
        title: "Gastlessen over Roma- en Sinti-geschiedenis nu ook in het voortgezet onderwijs",
        excerpt:
          "Samen met docenten ontwikkelden wij lesmateriaal over cultuur, geschiedenis en de Porajmos, inclusief een gastles door jongeren zelf.",
      },
      {
        date: "12 juni 2026",
        category: "Belangenbehartiging",
        title: "Onze inbreng bij het gemeentelijk inclusiebeleid",
        excerpt:
          "Vrouwen uit onze kringen spraken met wethouders over wonen, onderwijs en de omgang van instanties met de gemeenschap.",
      },
      {
        date: "28 mei 2026",
        category: "Gemeenschap",
        title: "Nieuwe vrouwenkring van start in Eindhoven",
        excerpt:
          "Vanaf juni komt er elke maand een groep bij elkaar in Eindhoven. Aanmelden is niet nodig — je bent welkom.",
      },
      {
        date: "6 mei 2026",
        category: "Bewustwording",
        title: "Filmavond en dialoog trok volle zaal",
        excerpt:
          "Ruim honderd bezoekers bekeken de documentaire en spraken daarna met makers, jongeren en beleidsmakers.",
      },
      {
        date: "14 april 2026",
        category: "Organisatie",
        title: "Jaarverslag 2025 gepubliceerd",
        excerpt:
          "Ons activiteitenverslag en de financiële verantwoording over 2025 zijn beschikbaar in de kennisbank.",
      },
    ],
    newsletterTitle: "Blijf op de hoogte",
    newsletterText: "Ontvang vier keer per jaar onze nieuwsbrief met projecten, evenementen en oproepen.",
  },
  evenementen: {
    eyebrow: "Evenementen",
    title: "Kom langs,",
    accent: "je bent welkom.",
    intro:
      "Vrouwenkringen, filmvertoningen, dialoogbijeenkomsten en trainingen. De meeste bijeenkomsten zijn gratis en vrij toegankelijk.",
    filterAll: "Alle types",
    cityLabel: "Stad",
    allCities: "Alle steden",
    countLabel: "bijeenkomsten",
    empty: "Geen bijeenkomsten die aan deze combinatie voldoen.",
    freeLabel: "Gratis",
    types: ["Vrouwenkring", "Film & dialoog", "Training", "Jongeren", "Herdenking"],
    items: [
      { day: "12", month: "AUG", type: "Herdenking", title: "Herdenking Porajmos", city: "Amsterdam", time: "19:00 – 21:00", text: "Jaarlijkse herdenking van de genocide op Roma en Sinti, met muziek en getuigenissen." },
      { day: "22", month: "AUG", type: "Vrouwenkring", title: "Vrouwenkring Rotterdam", city: "Rotterdam", time: "10:30 – 13:00", text: "Ontmoeting, koffie en een workshop over werk en opleiding." },
      { day: "05", month: "SEP", type: "Film & dialoog", title: "Filmavond: onze geschiedenis", city: "Utrecht", time: "19:30 – 22:00", text: "Documentaire met nagesprek onder leiding van jongeren uit de gemeenschap." },
      { day: "17", month: "SEP", type: "Training", title: "Training digitale vaardigheden", city: "Den Haag", time: "13:00 – 16:00", text: "Praktische training over DigiD, zorgportalen en online solliciteren." },
      { day: "28", month: "SEP", type: "Jongeren", title: "Jonge leiders — startbijeenkomst", city: "Eindhoven", time: "15:00 – 18:00", text: "Kennismaking met het leiderschapstraject voor jongeren van 15 tot 27 jaar." },
      { day: "09", month: "OKT", type: "Vrouwenkring", title: "Vrouwenkring Eindhoven", city: "Eindhoven", time: "10:30 – 13:00", text: "Nieuwe maandelijkse groep — binnenlopen mag, aanmelden hoeft niet." },
      { day: "21", month: "OKT", type: "Training", title: "Gastlestraining voor jongeren", city: "Amsterdam", time: "14:00 – 17:00", text: "Leer je eigen verhaal vertellen voor klassen in het voortgezet onderwijs." },
      { day: "07", month: "NOV", type: "Film & dialoog", title: "Dialoogbijeenkomst met gemeenten", city: "Utrecht", time: "16:00 – 19:00", text: "Beleidsmakers en gemeenschap in gesprek over inclusie en vertrouwen." },
    ],
    noteTitle: "Praktisch",
    notes: [
      "Alle locaties zijn rolstoeltoegankelijk. Laat het ons weten als je andere ondersteuning nodig hebt.",
      "Kinderen zijn welkom; bij de meeste bijeenkomsten is er opvang aanwezig.",
      "Heb je vervoer nodig? Neem contact op, wij denken graag mee.",
    ],
  },
  kennisbank: {
    eyebrow: "Kennisbank",
    title: "Kennis over Roma",
    accent: "en Sinti, vrij te gebruiken.",
    intro:
      "Publicaties, lesmateriaal, onderzoeken en handreikingen voor scholen, gemeenten, journalisten en de gemeenschap zelf.",
    filterAll: "Alle materialen",
    empty: "Nog geen materialen in deze categorie.",
    typeLabel: "Type",
    types: ["Publicatie", "Lesmateriaal", "Onderzoek", "Handreiking", "Verantwoording"],
    items: [
      { type: "Lesmateriaal", title: "Lesbrief: geschiedenis van Roma en Sinti", meta: "PDF · voortgezet onderwijs", text: "Vier lessen over herkomst, cultuur, vervolging en de positie van Roma en Sinti vandaag." },
      { type: "Handreiking", title: "Handreiking voor gemeenten", meta: "PDF · 24 pagina's", text: "Hoe bereik en betrek je Roma- en Sinti-inwoners bij beleid rond onderwijs, wonen en zorg?" },
      { type: "Onderzoek", title: "Onderwijsparticipatie van Roma-meisjes", meta: "Rapport · 2025", text: "Verkennend onderzoek naar oorzaken van schooluitval en werkzame interventies." },
      { type: "Publicatie", title: "Zurali — verhalen van sterke vrouwen", meta: "Digitaal magazine", text: "Portretten van vrouwen uit onze kringen in Nederland, Italië en Roemenië." },
      { type: "Handreiking", title: "Mediagids: schrijven over Roma en Sinti", meta: "PDF · voor journalisten", text: "Begrippen, veelvoorkomende stereotypen en aanbevelingen voor zorgvuldige berichtgeving." },
      { type: "Verantwoording", title: "Jaarverslag 2025", meta: "PDF · activiteiten & financiën", text: "Overzicht van onze activiteiten, resultaten en besteding van middelen in 2025." },
    ],
    themesTitle: "Veelgevraagde thema's",
    themes: [
      { title: "Geschiedenis & Porajmos", text: "Achtergrond over de vervolging van Roma en Sinti en de doorwerking daarvan." },
      { title: "Onderwijs", text: "Schooluitval, taalondersteuning en samenwerking tussen school en gezin." },
      { title: "Antiziganisme", text: "Herkennen en aanpakken van discriminatie tegen Roma en Sinti." },
      { title: "Cultuur & taal", text: "Romanes, muziek, tradities en het doorgeven daarvan aan jongeren." },
    ],
    requestTitle: "Materiaal aanvragen",
    requestText:
      "Wil je materiaal gebruiken voor je school, gemeente of organisatie? Neem contact op — wij denken graag mee over een gastles of workshop erbij.",
  },
  partners: {
    eyebrow: "Partners",
    title: "Samenwerken maakt",
    accent: "ons sterker.",
    intro:
      "Wij werken met gemeenten, fondsen, kennisinstellingen, scholen en Europese partnerorganisaties. Samen bereiken wij meer dan alleen.",
    groups: [
      { title: "Overheden & gemeenten", items: ["Gemeente Amsterdam", "Gemeente Rotterdam", "Gemeente Utrecht", "Gemeente Den Haag", "Ministerie van SZW"] },
      { title: "Fondsen", items: ["Erasmus+", "CERV-programma", "Oranje Fonds", "VSBfonds", "Lokale participatiefondsen"] },
      { title: "Kennis & onderwijs", items: ["Universitaire onderzoeksgroepen", "Scholen voortgezet onderwijs", "ROC's", "Bibliotheken"] },
      { title: "Europese partners", items: ["Roma-organisaties Italië", "Netwerk Roemenië", "Netwerk Servië", "Duitse Sinti-organisaties"] },
    ],
    whyTitle: "Wat een samenwerking oplevert",
    why: [
      { icon: "hands", title: "Toegang tot de gemeenschap", text: "Wij bereiken mensen die met reguliere kanalen niet bereikt worden." },
      { icon: "graduation", title: "Expertise", text: "Kennis over cultuur, taal en effectieve benadering, direct toepasbaar in beleid." },
      { icon: "globe", title: "Europees netwerk", text: "Directe lijnen met organisaties in meerdere Europese landen." },
      { icon: "shield", title: "Zorgvuldige uitvoering", text: "Transparante verantwoording en heldere afspraken over resultaten." },
    ],
    formTitle: "Word partner",
    formText: "Vertel ons kort waar je aan denkt. Wij nemen binnen vijf werkdagen contact op.",
    fields: { org: "Organisatie", name: "Contactpersoon", email: "E-mailadres", type: "Soort samenwerking", message: "Toelichting" },
    types: ["Lokaal project", "Onderzoek of kennisdeling", "Europees subsidietraject", "Financiële ondersteuning", "Anders"],
  },
  vrijwilligers: {
    eyebrow: "Vrijwilligers",
    title: "Jouw tijd maakt",
    accent: "direct verschil.",
    intro:
      "Vrijwilligers zijn onmisbaar bij onze bijeenkomsten, begeleiding en projecten. Ervaring is niet nodig — betrokkenheid wel.",
    rolesTitle: "Waar wij hulp bij zoeken",
    roles: [
      { title: "Begeleider vrouwenkring", time: "1 dagdeel per maand", text: "Help bij de organisatie van een maandelijkse bijeenkomst en ontvang deelnemers." },
      { title: "Huiswerkbegeleider", time: "2 uur per week", text: "Ondersteun kinderen en jongeren bij school, taal en huiswerk." },
      { title: "Tolk of taalmaatje", time: "In overleg", text: "Romanes, Roemeens, Servisch of Italiaans? Help bij gesprekken met instanties." },
      { title: "Evenementenhulp", time: "Per bijeenkomst", text: "Opbouw, ontvangst en catering bij filmavonden en herdenkingen." },
      { title: "Communicatie", time: "2 – 4 uur per week", text: "Help met sociale media, fotografie of het schrijven van nieuwsberichten." },
      { title: "Fondsenwerving", time: "In overleg", text: "Ondersteun bij subsidieaanvragen en contact met fondsen." },
    ],
    offerTitle: "Wat wij bieden",
    offer: [
      "Een warme gemeenschap en directe betrokkenheid bij de mensen om wie het gaat.",
      "Introductie, begeleiding en trainingen die je ook elders kunt gebruiken.",
      "Vergoeding van reiskosten en een vrijwilligersovereenkomst.",
      "De mogelijkheid om door te groeien naar een projectrol.",
    ],
    stepsTitle: "Zo werkt aanmelden",
    steps: [
      { step: "01", title: "Aanmelden", text: "Vul het formulier in of stuur ons een bericht." },
      { step: "02", title: "Kennismaking", text: "Een gesprek over jouw wensen, tijd en achtergrond." },
      { step: "03", title: "Introductie", text: "Je loopt mee bij een bijeenkomst en krijgt een begeleider." },
      { step: "04", title: "Aan de slag", text: "Je start in je rol, met vaste momenten voor overleg." },
    ],
    formTitle: "Meld je aan als vrijwilliger",
    fields: { name: "Naam", email: "E-mailadres", phone: "Telefoonnummer", role: "Rol waarin je wilt helpen", message: "Vertel iets over jezelf" },
  },
  doneren: {
    eyebrow: "Doneren",
    title: "Steun sterke vrouwen",
    accent: "en jongeren.",
    intro:
      "Met jouw donatie organiseren wij vrouwenkringen, studiebegeleiding, filmavonden en Europese uitwisselingen. Elke bijdrage komt direct ten goede aan onze programma's.",
    amountTitle: "Kies een bedrag",
    amounts: [
      { value: "€ 15", label: "Eén deelnemer", text: "Vervoer en catering voor één vrouw bij een bijeenkomst." },
      { value: "€ 40", label: "Een workshop", text: "Materialen voor een workshop digitale vaardigheden." },
      { value: "€ 100", label: "Een vrouwenkring", text: "Een complete maandelijkse bijeenkomst in één stad." },
      { value: "€ 250", label: "Een jongere", text: "Deelname van een jongere aan een Europese uitwisseling." },
    ],
    otherAmount: "Ander bedrag",
    monthly: "Maandelijks doneren",
    once: "Eenmalig doneren",
    donateCta: "Doneer nu",
    donateNote:
      "Het online donatieplatform wordt momenteel ingericht. Tot die tijd kun je rechtstreeks overmaken of contact met ons opnemen.",
    bankTitle: "Rechtstreeks overmaken",
    bank: [
      { label: "Ten name van", value: "Stichting Zurali Chej" },
      { label: "IBAN", value: "NL00 BANK 0000 0000 00" },
      { label: "Onder vermelding van", value: "Donatie + je naam" },
    ],
    waysTitle: "Andere manieren om te steunen",
    ways: [
      { icon: "heart", title: "Periodiek schenken", text: "Een periodieke schenking geeft ons zekerheid voor meerdere jaren." },
      { icon: "handshake", title: "Bedrijfspartnerschap", text: "Steun een project met middelen, expertise of een locatie." },
      { icon: "hands", title: "Doneer je tijd", text: "Vrijwilligers zijn net zo waardevol als financiële steun." },
      { icon: "spark", title: "Zamel in", text: "Organiseer een actie op je werk, school of verjaardag." },
    ],
    trustTitle: "Waar gaat jouw geld heen?",
    trust: [
      { value: "78%", label: "Direct naar programma's voor vrouwen en jongeren" },
      { value: "14%", label: "Kennisdeling, bewustwording en materiaal" },
      { value: "8%", label: "Organisatie en verantwoording" },
    ],
    trustNote:
      "Wij verantwoorden onze bestedingen jaarlijks in het jaarverslag, dat je vindt in de kennisbank.",
  },
  contact: {
    eyebrow: "Contact",
    title: "Wij horen graag",
    accent: "van je.",
    intro:
      "Een vraag over een bijeenkomst, een verzoek om samen te werken of behoefte aan ondersteuning? Schrijf ons — er antwoordt altijd een mens.",
    channels: [
      { icon: "mail", title: "Algemene vragen", value: "info@zuralichej.nl", note: "Reactie binnen twee werkdagen" },
      { icon: "hands", title: "Ondersteuning & begeleiding", value: "support@zuralichej.nl", note: "Vertrouwelijk, ook in Romanes" },
      { icon: "handshake", title: "Partners & pers", value: "partners@zuralichej.nl", note: "Samenwerking, media en fondsen" },
    ],
    formTitle: "Stuur een bericht",
    fields: { name: "Je naam", email: "E-mailadres", subject: "Onderwerp", message: "Bericht" },
    subjects: [
      "Ondersteuning voor mijzelf of mijn gezin",
      "Deelname aan een bijeenkomst",
      "Samenwerking of partnerschap",
      "Pers of onderzoek",
      "Vrijwilligerswerk",
      "Iets anders",
    ],
    privacy: "Wij gaan zorgvuldig met je gegevens om en delen ze nooit met derden (AVG).",
    visitTitle: "Bezoekadres",
    address: ["Stichting Zurali Chej", "Postbus 1234", "1000 AB Amsterdam", "Nederland"],
    hoursTitle: "Bereikbaarheid",
    hours: [
      { label: "Ma – do", value: "09:00 – 17:00" },
      { label: "Vrijdag", value: "09:00 – 13:00" },
      { label: "Telefoon", value: "+31 20 000 0000" },
    ],
    kvkTitle: "Gegevens",
    kvk: [
      { label: "KvK", value: "00000000" },
      { label: "RSIN", value: "000000000" },
      { label: "IBAN", value: "NL00 BANK 0000 0000 00" },
    ],
  },
  footer: {
    about:
      "Stichting Zurali Chej is een door Roma geleide organisatie die zich inzet voor Roma- en Sinti-vrouwen en jongeren in Nederland en Europa.",
    newsletterTitle: "Nieuwsbrief",
    newsletterText: "Vier keer per jaar het laatste nieuws in je inbox.",
    newsletterPlaceholder: "Je e-mailadres",
    newsletterButton: "Aanmelden",
    newsletterSuccess: "Dank je wel — je bent aangemeld.",
    rights: "Alle rechten voorbehouden.",
    privacy: "Privacyverklaring",
    accessibility: "Toegankelijkheid",
  },
};

export type Dict = typeof nl;
