/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingPageRouteImport } from './routes/landing-page'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BecomeAHostRouteImport } from './routes/become-a-host'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const LandingPageRoute = LandingPageRouteImport.update({
  id: '/landing-page',
  path: '/landing-page',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAHostRoute = BecomeAHostRouteImport.update({
  id: '/become-a-host',
  path: '/become-a-host',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-host': typeof BecomeAHostRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/landing-page': typeof LandingPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-host': typeof BecomeAHostRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/landing-page': typeof LandingPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-host': typeof BecomeAHostRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/landing-page': typeof LandingPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-a-host'
    | '/categories'
    | '/contact'
    | '/events'
    | '/landing-page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-a-host'
    | '/categories'
    | '/contact'
    | '/events'
    | '/landing-page'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-a-host'
    | '/categories'
    | '/contact'
    | '/events'
    | '/landing-page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomeAHostRoute: typeof BecomeAHostRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  LandingPageRoute: typeof LandingPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing-page': {
      id: '/landing-page'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-host': {
      id: '/become-a-host'
      path: '/become-a-host'
      fullPath: '/become-a-host'
      preLoaderRoute: typeof BecomeAHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomeAHostRoute: BecomeAHostRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  LandingPageRoute: LandingPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
